language: cpp

sudo: required
dist: trusty

os:
  - linux
  - osx

env:
  - CONFIG=Release
  - CONFIG=Debug

branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?$/
    - travis-ci

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         wget --no-check-certificate https://cmake.org/files/v3.3/cmake-3.3.0-Linux-x86_64.tar.gz
      && tar -xzf cmake-3.3.0-Linux-x86_64.tar.gz
      && sudo cp -fR cmake-3.3.0-Linux-x86_64/* /usr
      && sudo apt-get install software-properties-common
      && sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      && sudo apt-add-repository -y ppa:beineri/opt-qt562-trusty
      && sudo apt-get -qq update
      && sudo apt-get -qq install gcc-4.9 g++-4.9 libgl1-mesa-dev libglu1-mesa-dev
      && sudo apt-get -qq install qt56location qt56multimedia qt56sensors qt56svg qt56tools qt56webchannel
      && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 50
      && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
      ;
    else
         brew update
      && curl -O https://raw.githubusercontent.com/Homebrew/homebrew-core/106d0878ee812cb8f5c403f717bdebe836445aee/Formula/qt5.rb
      && brew install ./qt5.rb
      && export OPENSSL_ROOT_DIR=/usr/local/opt/openssl
      && chmod -R 755 /usr/local/opt/qt5/*
      ;
    fi

script:
  # Note: on Linux, the linking of CellMLTextView_conversiontests and
  #       CellMLTextView_parsingtests results in an error regarding
  #       __cxa_throw_bad_array_new_length@Qt_5 not being defined in
  #       libqscintilla2_qt5.so.13. This is most likely related to our use of
  #       GCC/G++ 4.9. However, a simple workaround is to build QScintilla, so
  #       this is what we are doing here...
  -    cd build
    && if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         cmake -DCMAKE_BUILD_TYPE=$CONFIG -DENABLE_TRAVIS_CI=ON -DCMAKE_PREFIX_PATH=/opt/qt56/lib/cmake -DUSE_PREBUILT_QSCINTILLA_PACKAGE=OFF -DENABLE_SAMPLE_PLUGINS=ON -DENABLE_TEST_PLUGINS=ON -DENABLE_TESTS=ON ..
         ;
       else
         cmake -DCMAKE_BUILD_TYPE=$CONFIG -DENABLE_TRAVIS_CI=ON -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake -DENABLE_SAMPLE_PLUGINS=ON -DENABLE_TEST_PLUGINS=ON -DENABLE_TESTS=ON ..
         ;
       fi
    && make -j 3
    && cd ..
    && if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         build/bin/runtests
         ;
       else
         build/OpenCOR.app/Contents/MacOS/runtests
         ;
       fi

notifications:
  email: team@opencor.ws
