language: cpp

branches:
  only:
    - master

os:
  - linux
  - osx

env:
  - CONFIG=Release
  - CONFIG=Debug

install:
  -    if [ "`uname -s`" = "Linux" ] ; then
            sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
         && sudo apt-get -qq update
         && sudo apt-get -qq install g++-4.8
         && export CXX="g++-4.8"
         && export CC="gcc-4.8"
         ;
       fi
    && if [ "`uname -s`" = "Linux" ] ; then
            sudo apt-get -qq update
         && sudo apt-get -qq install libc6-i386
         && wget http://www.cmake.org/files/v3.0/cmake-3.0.1-Linux-i386.tar.gz
         && tar -xzf cmake-3.0.1-Linux-i386.tar.gz
         && sudo cp -fR cmake-3.0.1-Linux-i386/* /usr
         ;
       else
            brew update
         && brew unlink cmake
         && brew install cmake
         ;
       fi
    && if [ "`uname -s`" = "Linux" ]; then
            sudo apt-add-repository -y ppa:beineri/opt-qt532
         && sudo apt-get -qq update
         && sudo apt-get -qq install qt53tools qt53svg qt53webkit
         ;
       else
            brew update
         && brew install qt5
         && chmod -R 755 /usr/local/opt/qt5/*
         ;
       fi

script:
  -    cd build
    && if [ "`uname -s`" = "Linux" ]; then
         cmake -DCMAKE_BUILD_TYPE=$CONFIG -DCMAKE_PREFIX_PATH=/opt/qt53/lib/cmake -DENABLE_TESTS=ON -DENABLE_SAMPLES=ON ..
         ;
       else
         cmake -DCMAKE_BUILD_TYPE=$CONFIG -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake -DENABLE_TESTS=ON -DENABLE_SAMPLES=ON ..
         ;
       fi
    && make
    && if [ "`uname -s`" = "Linux" ]; then
         cd bin
         ;
       else
         cd OpenCOR.app/Contents/MacOS
         ;
       fi
    && ./runtests

notifications:
  email:
    - team@opencor.ws
    - agarny@hellix.com
