#!/bin/sh

## CMake's FindPythonLibs id broken under OS/X and variables
## must be manually set as appropriate.

rm -f build/*
cd build
cmake -G Ninja    \
      -DPYTHON_INCLUDE_DIR=/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/include/python2.7  \
      -DPYTHON_LIBRARY=/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib \
      ..
ninja
